// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // Manual sidebar for Physical AI & Humanoid Robotics textbook
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro', 'physical-ai-foundations'],
    },
    {
      type: 'category',
      label: 'Module 1: Robotic Nervous System (ROS 2)',
      items: [
        'ros2-fundamentals',
        'ros2-nodes-topics-services',
        'rclpy-integration',
        'urdf-humanoids',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      items: [
        'gazebo-simulation',
        'unity-visualization',
        'sensor-simulation',
        'physics-collision-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'nvidia-isaac-platform',
        'isaac-ai-workflows',
        'robot-brain-integration',
        'isaac-simulation-environments',
        'ros2-isaac-integration',
        'deployment-scenarios',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'introduction-to-vla-systems',
        'vision-language-models',
        'action-planning',
        'multimodal-interaction',
        'vla-simulation-examples',
        'vla-ros-integration',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Capstone: Autonomous Humanoid',
    //   items: [
    //     'capstone-overview',
    //     'simulated-robot-control',
    //     'path-planning-obstacle-navigation',
    //     'object-identification-manipulation',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Hardware & Deployment',
    //   items: [
    //     'hardware-requirements',
    //     'workstation-setup',
    //     'edge-computing-kits',
    //     'deployment-scenarios',
    //   ],
    // },
  ],
};

export default sidebars;
